# Generated by Django 4.0.5 on 2022-08-02 17:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trustee', models.BooleanField(default=False)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('admin', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('type', models.CharField(max_length=255, null=True)),
                ('location_address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('trustees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('size', models.CharField(max_length=255)),
                ('docs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('gdpr_agreed', models.BooleanField(default=False)),
                ('privacy_agreed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewRequest',
            fields=[
                ('reference', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner_approved', models.BooleanField(default=False)),
                ('confirmations', models.IntegerField(default=0)),
                ('request_address', models.CharField(max_length=255)),
                ('request_Status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProofSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, null=True, size=None)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('degreeType', models.CharField(max_length=255, null=True)),
                ('degree_name', models.CharField(max_length=255, null=True)),
                ('course_name', models.CharField(max_length=255, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degreeClass', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('affirmationStatement', models.TextField(blank=True, max_length=1000, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.applicant')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='ProofRequest',
            fields=[
                ('reference', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('completion_year', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_month', models.CharField(blank=True, max_length=255, null=True)),
                ('deg_type', models.CharField(blank=True, max_length=255, null=True)),
                ('deg_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('deg_class', models.CharField(blank=True, max_length=255, null=True)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('student_num', models.CharField(blank=True, max_length=255, null=True)),
                ('date_awarded', models.CharField(blank=True, max_length=255, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('signers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None)),
                ('affirmation_statement', models.TextField(blank=True, max_length=1000, null=True)),
                ('has_affirmation', models.BooleanField(default=False)),
                ('required_signers', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_signers', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('signatures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None)),
                ('data_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.applicant')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.certificate')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='PendingViewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_requests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PendingProofRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_requests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None)),
                ('trustee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicertverify.applicant')),
            ],
        ),
    ]
