# Generated by Django 4.0.5 on 2022-08-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicertverify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proofrequest',
            old_name='transaction_hash',
            new_name='tx_hash',
        ),
    ]
