# Generated by Django 4.0.5 on 2022-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicertverify', '0002_rename_transaction_hash_proofrequest_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofrequest',
            name='tx_hash',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
