version: "3"
services:


       unicertverify_configservice:
           container_name: unicertverify_configservice
           image: latest/unicertverify_configservice
           command: postgres://unicertverify@postgres:5432/unicertverify
           environment: 
              NODE_ENV: development
              BASE_URL: http://localhost
              
              PORT: 8000
              API_VERSION: v1
  
           restart: always
           build:
              context: ./unicertverify_configuration_service
              dockerfile: ./Dockerfile
           ports:
             - "8000:8000"
           links:
             - postgres


       unicertverify_txservice:
           container_name: unicertverify_txservice
           image: latest/unicertverify_txservice
           environment: 
              NODE_ENV: development
              BASE_URL: http://localhost
              PORT: 4000
              MONGO_URL: mongodb://mongo:27017/mydb
              API_VERSION: v1
              

           restart: always
           build:
              context: ./unicertverify_transaction_service
              dockerfile: ./Dockerfile
           ports:
             - "4000:4000"
           links:
             - mongo

       



       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'
      
       postgres:
             container_name: postgres
             image: postgres
             environment:
                POSTGRES_USER: unicertverify
                POSTGRES_PASSWORD: unicertverify_access
                POSTGRES_DB: unicertverify
             volumes:
               - ./data/db:/var/lib/postgresql/data
             ports:
               - '5432:5432'


       


       unicertverify_ui:
          container_name: unicertverify_ui
          image: latest/unicertverify_ui
          environment: 
            NODE_ENV: development
            API_URL: http://localhost:4000
            PORT: 3000

          restart: always
          build: 
            context: ./unicertverify_interface
            dockerfile: ./Dockerfile
          ports:
            - "3000:3000"
          links:
            - "unicertverify_txservice:be"
